sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-069.pdf --upload --lsstdoc DMTN-069.tex --env=travis --ltd-product dmtn-069"
env:
  global:
    - secure: "CuqBWzkeeQDWevFzODtrAvX7hdCaIWEKsBXI4GyWJZH1DmEMCPRar96AOtf34UYkV04bz+kNHODi4eRGBZHxHI3sbHENB/ChnDEVH+g2/z6R4IBdmFCQC8en5bNhLd4lTqDRiFZs6YEG47fyoyRuklvbC2MlFsB8XrR+h+gi9c6wMrI27zSVNzZ5ByHz7cBRxy1SqC4tsEAaAa9LnrdlXj+QZpBFoLnTqh7/yrq14fyFZ6Cc0bakosQmJiZJGjzpcFhjwVZ3+NQpz9MnJG7ZbEQtkt2hVokxFVHmN0wDXAACPXRTQlOOl20wiyisMOowdpdwfNZdye1UowBSHgrvERhwkYqoFfF5Ronp1u/6u0HZN20dE0+4LTdR20DXpEeJSI5lA//x+jDZxgq8IG69wSu71xsZshhxZzhHCfd2jcTQHGgemeBBGIGC+HYFgWYNUOP3iYcQiWBImzzOY/6yyTbynZZoYWH1eVvZHgjh0KM9cBpuZ9SpIgP65J2gi8eVlhwpYwlh648dlpCrTmnJ3z6kNfqMdBdBv+pJTAN1avr+gN/GoVW9osaUUK5UkMsljb/dl+QgnczBDbfYVCe42vgbu0gylSvhbjPb2G4AdrzFhYUC1/oBT3QEhDTOTV8tYDBj280lTzACKLmUNX6DPjkpSd4RlQfa/69lsld9mog="
    - secure: "ueWyNYRulUVSh8t1extSQwzD3ykZ4YWrLGkAsCgdWhDBqcTH2MZmVENQW35eZr9iloPry14S8eYmOYAroLu+jSg/Dmjsn3MuhfpVhs4yQPU8YVPdELy+yjHXI4BHzFngQe7XQ6UZynoZpR01IkthcUCn6f347Kg51AR16Jeg6VeuuLAYfNNKY6gtsYyRpE+FgK7KAPLKIZa+We8IF3PocUkT47f8eeySBpRiqCOPWp7n9IQCwhX8lN1VMD5Vm3OVbLSRnPqDZCymbmSIM58Y6P45r6o78QDMb/i6XTlvqVGgETW8QbCaCp4JsKhbFENlUgdba1CN1ayBYcWaGdvRFsicN5bC5eidgus1EuOPEZ3/VCEJ+LtrwWTnl45N1aP2X3pOJIHnbGed31IILdAeHolj1Chx6lIVGTEyEIsJ0wfZjVokAEaz/HrK4z4geSggCiRV7FuZALoWgjlupbuMV4SNjZyWXkRHb1Oq5sPD/AqnAafz05weEo0ZKZeTI8CtXY+MMggqzlGpzZTa30L5gqfZsjxPuekwGuaywX8kf109Knui6XDbZ51XHieGuR3UChXp5RoCrzNCNDga0SfYQTYgfNUlG1ps3oAHr70iNEE1HzFvanGFqt5MwFzklakvazytKVnSFJfOPtexB2vuOi8ls31vWGlTI2pRVjiw2Ho="
